[package]
name = "workspace"
version = "0.1.0"
edition = "2021"

[dependencies]
db          = { path = "../db" }
serde       = { workspace = true }
serde_json  = { workspace = true }
uuid        = { workspace = true }
anyhow      = { workspace = true }
tokio       = { workspace = true }
tracing     = { workspace = true }
toml        = "0.8"
notify      = { version = "6" }
sqlx        = { version = "0.8", features = ["sqlite", "runtime-tokio-rustls", "uuid", "migrate", "chrono"] }
